all : coarse_grained.cpp fine_grained.cpp optimistic.cpp
	g++ -o coarse_grained coarse_grained.cpp -lpthread
	g++ -o fine_grained fine_grained.cpp -lpthread
	g++ -o optimistic optimistic.cpp -lpthread